### ISSUE TITLE
Journal app will not run

### ISSUE THREAD

**Issue by vinyldarkscratch** [vinyldarkscratch/synglechance#12]
The `Journal` class inherits from the `QWidget` class, and to initialize it, requires an argument.

```
Traceback (most recent call last):
  File "journal.py", line 74, in <module>
    journal = Journal()
  File "journal.py", line 36, in __init__
    super().__init__(*args, **kwargs)
TypeError: super() takes at least 1 argument (0 given)
```

**Comment by vinyldarkscratch** [comment]
I'm an idiot, I was running it with Python 2, not Python 3.
